name: taxi24-prod
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    container_name: taxi24-prod-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15
    container_name: taxi24-prod-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  postgres-prod-data:
