name: taxi24-dev
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    container_name: taxi24-dev-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      postgres-e2e:
        condition: service_healthy
    command: sh -c "npm run seed && npm run start:dev"
  postgres:
    image: postgres:15
    container_name: taxi24-dev-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 5
  postgres-e2e:
    image: postgres:15
    container_name: taxi24-e2e-postgres
    env_file:
      - .env.e2e
    ports:
      - "5433:5432"
    volumes:
      - postgres-e2e-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  postgres-dev-data:
  postgres-e2e-data:
